"""HTML email renderer for digest output.

Bias tag colors
---------------
Colors for each bias lean label are read from settings.yaml under
``delivery.email.bias_tag_colors``. This allows operators to change the
palette without touching Python. Hardcoded defaults are used as fallbacks
so the renderer works even if the settings key is missing.

Example settings.yaml entry::

    delivery:
      email:
        bias_tag_colors:
          left:         "#1565c0"
          center-left:  "#1976d2"
          center:       "#388e3c"
          center-right: "#e64a19"
          right:        "#b71c1c"
          unknown:      "#757575"
"""

from __future__ import annotations

import html
from typing import Optional

from config.loader import get_settings
from summarizer.summarizer import SummarizedCluster

# Fallback colors used when settings.yaml does not define bias_tag_colors.
_DEFAULT_BIAS_COLORS: dict[str, str] = {
    "left":          "#1565c0",
    "center-left":   "#1976d2",
    "center":        "#388e3c",
    "center-right":  "#e64a19",
    "right":         "#b71c1c",
    "unknown":       "#757575",
}
_DEFAULT_BIAS_LABELS: dict[str, str] = {
    "left":          "Left",
    "center-left":   "Lean Left",
    "center":        "Center",
    "center-right":  "Lean Right",
    "right":         "Right",
    "unknown":       "Unknown",
}


def _get_bias_colors() -> dict[str, str]:
    """Return bias tag colors from settings.yaml, falling back to defaults."""
    settings = get_settings()
    return (
        settings.get("delivery", {})
               .get("email", {})
               .get("bias_tag_colors", _DEFAULT_BIAS_COLORS)
    )


def _bias_tag(lean: str) -> str:
    """Render a colored HTML badge for a bias lean label."""
    colors = _get_bias_colors()
    color = colors.get(lean, _DEFAULT_BIAS_COLORS["unknown"])
    label = _DEFAULT_BIAS_LABELS.get(lean, lean.title())
    return (
        f'<span style="display:inline-block;padding:2px 8px;border-radius:3px;'
        f'background:{color};color:#fff;font-size:11px;font-weight:600;">'
        f'{html.escape(label)}</span>'
    )


class EmailRenderer:
    """Renders a list of SummarizedClusters into an HTML email digest."""

    def render(self, summaries: list[SummarizedCluster], period: str) -> str:
        """Return a complete HTML email string for the given digest period."""
        settings = get_settings()
        title = f"NewsBot — {period.title()} Digest"
        stories_html = "\n".join(
            self._render_story(s) for s in summaries
        )
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{html.escape(title)}</title>
  <style>
    body {{ font-family: Georgia, serif; max-width: 680px; margin: 0 auto;
            padding: 24px 16px; color: #1a1a1a; background: #fafafa; }}
    h1   {{ font-size: 22px; border-bottom: 2px solid #ddd; padding-bottom: 8px; }}
    .story {{ margin-bottom: 32px; padding: 16px; background: #fff;
              border: 1px solid #e0e0e0; border-radius: 4px; }}
    .story h2  {{ font-size: 17px; margin: 0 0 8px; }}
    .story p   {{ font-size: 14px; line-height: 1.6; margin: 8px 0; color: #333; }}
    .meta      {{ font-size: 12px; color: #666; margin-top: 10px; }}
    .bias-note {{ font-size: 12px; color: #555; font-style: italic;
                  margin-top: 8px; border-left: 3px solid #ddd; padding-left: 8px; }}
  </style>
</head>
<body>
  <h1>{html.escape(title)}</h1>
  {stories_html}
  <p style="font-size:11px;color:#999;margin-top:32px;">Generated by NewsBot</p>
</body>
</html>"""

    def _render_story(self, story: SummarizedCluster) -> str:
        source_tags = " ".join(
            f'<span style="font-size:11px;background:#eee;padding:1px 6px;\
 border-radius:3px;">{html.escape(s)}</span>'
            for s in sorted(story.sources)
        )
        bias_note_html = ""
        if story.bias_notes:
            bias_note_html = (
                f'<div class="bias-note">'
                f'<strong>Framing note:</strong> {html.escape(story.bias_notes)}'
                f'</div>'
            )
        tiers_str = ", ".join(story.tiers)
        return f"""<div class="story">
  <h2>{html.escape(story.headline)}</h2>
  <p>{html.escape(story.summary)}</p>
  <div class="meta">
    {source_tags}
    &nbsp;&middot;&nbsp;
    <span>{story.source_count} source{'s' if story.source_count != 1 else ''}</span>
    &nbsp;&middot;&nbsp;
    <span>{html.escape(tiers_str)}</span>
  </div>
  {bias_note_html}
</div>"""
